project:
  type: website
  output-dir: docs
  
website:
  title: "Imani Oluwafumailayo Maliti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: instagram
        href: https://twitter.com/
      - icon: github
        menu:
          - text: View Source
            url:  https://github.com/YOURUSERNAME/YOURREPO

format:
  html:
    theme: sketchy
    toc: true

editor: source

